change script

diff --git a/bin/search b/bin/search
--- a/bin/search
+++ b/bin/search
@@ -1,4 +1,9 @@
-# TODO: Needs modification 
+#!/bin/bash
+# search
+
+
+# Stop on errors
+# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
 set -Eeuo pipefail
 
 usage() {
@@ -18,10 +23,7 @@ case $1 in
             echo "Error: search server is already running"
             exit 1
         else
-            echo "starting search server ...
-            + mkdir -p var/log
-            + rm -f var/log/search.log
-            + flask --app search run --host 0.0.0.0 --port 8000 &> var/log/search.log &"
+            echo "starting search server ..."
             mkdir -p var/log
             rm -f var/log/search.log
             flask --app search run --host 0.0.0.0 --port 8000 &> var/log/search.log &
@@ -39,20 +41,15 @@ case $1 in
   ;;
 
   "stop")
-    echo "stopping search server ...
-    + pkill -f 'flask --app search run --host 0.0.0.0 --port 8000' || true"
+    echo "stopping search server ..."
     pkill -f 'flask --app search run --host 0.0.0.0 --port 8000' || true
   ;;
 
   "restart")
-    echo "stopping search server ...
-    + pkill -f 'flask --app search run --host 0.0.0.0 --port 8000' || true"
+    echo "stopping search server ..."
     pkill -f 'flask --app search run --host 0.0.0.0 --port 8000' || true
 
-    echo "starting search server ...
-    + mkdir -p var/log
-    + rm -f var/log/search.log
-    + flask --app search run --host 0.0.0.0 --port 8000 &> var/log/search.log &"
+    echo "starting search server ..."
     mkdir -p var/log
     rm -f var/log/search.log
     flask --app search run --host 0.0.0.0 --port 8000 &> var/log/search.log &
